id: IB7B0E406
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T13:07:25+00:00'
last_modified: '2022-06-08T05:32:28.364459+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5377
  title: ཕར་ཕྱིན་མཐའ་དཔྱོད་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '8609':
      image_group_id: I1KG5393
      title: Volume 1 of phar phyin mtha' dpyod
      total_pages: 618
      order: 1
      base_file: 8609.txt
    ED7D:
      image_group_id: I1KG5394
      title: Volume 2 of phar phyin mtha' dpyod
      total_pages: 450
      order: 2
      base_file: ED7D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
